# Prometheus Configuration for Cybernetic Staging
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: staging
    cluster: cybernetic-vsm

rule_files:
  # Alert rules for VSM system health
  - "alerts/*.yml"

scrape_configs:
  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 30s
    metrics_path: '/metrics'
    honor_labels: true

  # Cybernetic application metrics (when deployed)
  - job_name: 'cybernetic-app'
    static_configs:
      - targets: ['cybernetic:4000']
    scrape_interval: 15s
    metrics_path: '/metrics'
    honor_labels: true
    # Add VSM system labels
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: cybernetic

  # RabbitMQ management metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # PostgreSQL metrics (if exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Redis metrics (if exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s
    metrics_path: '/metrics'