name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      rabbitmq:
        image: rabbitmq:3.13-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd="rabbitmq-diagnostics -q ping"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '27'
      
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Wait for RabbitMQ
        run: |
          echo "Waiting for RabbitMQ to be ready..."
          for i in {1..60}; do
            nc -z 127.0.0.1 5672 && echo "RabbitMQ is ready!" && exit 0
            echo "Attempt $i/60: RabbitMQ not ready yet..."
            sleep 1
          done
          echo "RabbitMQ failed to start" && exit 1
      
      - name: Compile
        run: mix compile
      
      - name: Run Core Tests
        run: MIX_ENV=test mix cyb.test.core
      
      - name: Run Transport Tests
        run: MIX_ENV=test AMQP_HOST=localhost mix cyb.test.io
      
      - name: Run Goldrush Tests
        run: MIX_ENV=test mix cyb.test.gr
      
      - name: Run System Probe
        run: MIX_ENV=test AMQP_HOST=localhost mix cyb.probe

  format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '27'
      
      - name: Check formatting
        run: mix format --check-formatted